{% set name = "graph-pes" %}
{% set version = "0.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/graph_pes-{{ version }}.tar.gz
  sha256: 72f279abd11875db1f202c793e85acca5118d9a5381506c17739d9d838791020

build:
  entry_points:
    - graph-pes-train = graph_pes.scripts.train:main
    - graph-pes-id = graph_pes.scripts.id:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - ase ==3.22.1
    - dacite
    - data2objects
    - e3nn
    - load-atoms >=0.3.5
    - locache
    - numpy
    - python >={{ python_min }}
    - pytorch
    - pytorch-lightning
    - rich
    - scikit-learn
    - wandb

test:
  imports:
    - graph_pes
  commands:
    - pip check
    - graph-pes-train --help
    - graph-pes-id --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://jla-gardner.github.io/graph-pes/
  dev_url: https://github.com/jla-gradner/graph-pes
  summary: Potential Energy Surfaces on Graphs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
