{% set name = "graph-pes" %}
{% set version = "0.0.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/graph_pes-{{ version }}.tar.gz
  sha256: 2b05dc27c8335f1fa8e961a66ec5bc0138817a4d40ebc5da2452ff801248faae

build:
  entry_points:
    - graph-pes-train = graph_pes.scripts.train:main
    - graph-pes-id = graph_pes.scripts.id:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - pyright >=1.1.394
    - vesin >=0.3.2
    - ase
    - dacite
    - data2objects >=0.1.0
    - e3nn <=0.5.3
    - load-atoms >=0.3.9
    - locache >=4.0.2
    - numpy
    - python >={{ python_min }}
    - pytorch
    - pytorch-lightning
    - rich
    - scikit-learn
    - wandb

test:
  imports:
    - graph_pes
  commands:
    - pip check
    - graph-pes-train --help
    - graph-pes-id --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://jla-gardner.github.io/graph-pes/
  dev_url: https://github.com/jla-gradner/graph-pes
  summary: Potential Energy Surfaces on Graphs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
